```{r setup, include=FALSE}
# load packages
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggcorrplot)
library(tinytex)
library(stringr)
library(tidyverse)
library(pander)
library(lubridate)
library(mice)
library(plotly)
library(readr)
library(bupaR)
library(eventdataR)
library(xesreadR)
library(edeaR)
library(processmapR)
library(processmonitR)

#install.packages("bupaR")
#install.packages("eventdataR")
#install.packages("xesreadR")
#install.packages("edeaR")
#install.packages("processmapR")
#install.packages("processmonitR")

```

```{r}
# load data / source loadscript
data <- read_csv("data.csv")

```

```{r}
# bewerkingen data
data %>%
  group_by(`case GR-Based Inv. Verif.`) %>%
  summarise(aantal = n())

data %>%
  group_by(`case Goods Receipt`) %>%
  summarise(aantal = n())

data %>%
  group_by(`case Document Type`) %>%
  summarise(aantal = n())

data <- data %>%
  mutate(lifecycle_id = "complete")

```

```{r}
# event log building
data$`event time:timestamp` <- dmy_hms(data$`event time:timestamp`)

summary(data)

eventlog <- bupaR::simple_eventlog(eventlog = data, case_id = "case concept:name", activity_id = "event concept:name", timestamp = "event time:timestamp")

```

```{r}
#om de cornerstones te bekijken

cornerstones <- unique(data$`event concept:name`)
print(cornerstones)
```

```{r}
# Bekijken de key documents & tables
documents <- unique(data$`case Purch. Doc. Category name`)
print(documents)
```

```{r}
# Exploratory analysis (Dongho)

# Remove special characters from raw data (activity_frequency() doesn't work on the original eventlog)
data_exploratory <- data
colnames(data_exploratory) <- gsub("[^[:alnum:]_]", "", colnames(data))

# Create simple_eventlog without special characters
eventlog_exploratory <- simple_eventlog(
  data_exploratory, 
  case_id = "caseconceptname",
  activity_id = "eventconceptname",
  resource_id = "eventorgresource",
  timestamp = "eventtimetimestamp"
  )

# Activity frequency
eventlog_exploratory %>% activity_frequency(level = "activity") %>% plot()
eventlog_exploratory %>% activity_frequency(level = "trace") %>% plot()
eventlog_exploratory %>% activity_frequency(level = "case")
eventlog_exploratory %>% activity_frequency(level = "log")

# Activity presence (= in what percentage of cases is each activity type present)
activity_presence(eventlog_exploratory)

# End activities 
eventlog_exploratory %>% end_activities(level = "log")
eventlog_exploratory %>% end_activities(level = "activity")

# Idle time (amount of time that no activity occurs)
eventlog_exploratory %>% idle_time(level = "log", units = "hours")
eventlog_exploratory %>% idle_time(level = "case", units = "weeks")
#trace_idle_time <- eventlog_exploratory %>% idle_time(level = "trace", units = "weeks")
#write_csv(trace_idle_time, "trace_idle_time.csv")
eventlog_exploratory %>% idle_time(level = "resource", units = "hours")

# Number of repetitions
eventlog_exploratory %>% number_of_repetitions(level = "log")
eventlog_exploratory %>% number_of_repetitions(level = "case")
eventlog_exploratory %>% number_of_repetitions(level = "activity") %>% plot()

# Number of self loops
eventlog_exploratory %>% number_of_selfloops(level = "log", type = "repeat")
eventlog_exploratory %>% number_of_selfloops(level = "case", type = "repeat")
eventlog_exploratory %>% number_of_selfloops(level = "activity", type = "repeat") %>% plot()

# Number of traces
number_of_traces(eventlog_exploratory)

# Processing time
eventlog_exploratory %>% processing_time(level = "activity", units = "hours")
```

```{r}
# Clusteren van bepaalde activiteiten om de visualisaties makkelijker te maken

eventlog_cluster <- eventlog_exploratory %>%
  mutate(eventconceptname = case_when(
    eventconceptname %in% c("SRM: Created", "SRM: Change was Transmitted", "SRM: Document Completed", "SRM: Awaiting Approval", "SRM: Complete", "SRM: In Transfer to Execution Syst.", "SRM: Ordered", "SRM: Deleted", "SRM: Transaction Completed", "SRM: Incomplete", "SRM: Held", "SRM: Transfer Failed (E.Sys.)") ~ "SRM",
    eventconceptname %in% c("Change Currency", "Change Price", "Change Quantity") ~ "Change price/quantity/currency",
    TRUE ~ eventconceptname
  ))
```

```{r}
#Checken of er een correcte procesuitvoering wordt uitgevoerd (zie projectbeschrijving die 4 regels)

eventlog_cluster_before <- eventlog_cluster %>% filter(caseItemCategory == "3-way match, invoice before GR")

eventlog_cluster_before2 <- eventlog_cluster_before %>%
  filter(caseGRBasedInvVerif == FALSE)

eventlog_cluster_after <- eventlog_cluster %>%
  filter(caseItemCategory == "3-way match, invoice after GR")

eventlog_cluster_after2 <- eventlog_cluster_after %>%
  filter(caseGRBasedInvVerif == TRUE)

eventlog_cluster_twoway <- eventlog_cluster %>%
  filter(caseItemCategory == "2-way match")

eventlog_cluster_twoway2 <- eventlog_cluster_twoway %>%
  filter(caseGoodsReceipt == FALSE)

eventlog_cluster_consignment <- eventlog_cluster %>%
  filter(caseItemType == "Consignment")
```

```{r}
#filteren om te kijken of er een goods receipt aanwezig is

eventlog_cluster_before_check <- eventlog_cluster_before3 %>%
  filter(caseGoodsReceipt == TRUE)
```

```{r}
#Precedence matrix opmaken voor de regel van de factuur voor de GR te analyseren.
eventlog_cluster_before3 <- eventlog_cluster_before %>%
  filter(eventconceptname %in% c("Vendor creates invoice", "Record Goods Receipt", "Record Invoice Receipt"))



eventlog_cluster_before3 %>% precedence_matrix(type = "relative-antecedent") %>% plot()
```

```{r}
#kijken of de bedragen overeenkomen voor invoice before GR
eventlog_cluster_beforebedragen <- eventlog_cluster_before %>%
  filter(eventconceptname %in% c("Vendor creates invoice", "Record Goods Receipt", "Record Invoice Receipt", "Create Purchase Order Item")) %>%
  select(caseconceptname, eventconceptname, eventCumulativenetworthEUR, eventtimetimestamp)

eventlog_cluster_widebeforebedragen <- eventlog_cluster_beforebedragen %>%
  group_by(caseconceptname) %>%
  summarise(PO_value = max(eventCumulativenetworthEUR[eventconceptname == "Create Purchase Order Item"], na.rm = TRUE),
            GR_value = max(eventCumulativenetworthEUR[eventconceptname == "Record Goods Receipt"], na.rm = TRUE),
            Invoice_value = max(eventCumulativenetworthEUR[eventconceptname %in% c("Vendor creates invoice", "Record Invoice Receipt")], na.rm = TRUE))

eventlog_cluster_widebeforebedragen <- eventlog_cluster_widebeforebedragen %>%
  mutate(three_way_match = PO_value == GR_value & GR_value == Invoice_value)

print(eventlog_cluster_widebeforebedragen)

false_count_before_threeway <- sum(eventlog_cluster_widebeforebedragen$three_way_match == FALSE, na.rm = TRUE)

```

```{r}
#Precedence matrix opmaken voor de regel van de factuur na de GR te hebben
eventlog_cluster_after3 <- eventlog_cluster_after %>%
  filter(eventconceptname %in% c("Vendor creates invoice", "Record Goods Receipt", "Record Invoice Receipt"))



eventlog_cluster_after3 %>% precedence_matrix(type = "relative-antecedent") %>% plot()
```

```{r}
#kijken of de bedragen overeenkomen voor invoice after GR
eventlog_cluster_afterbedragen <- eventlog_cluster_after %>%
  filter(eventconceptname %in% c("Vendor creates invoice", "Record Goods Receipt", "Record Invoice Receipt", "Create Purchase Order Item")) %>%
  select(caseconceptname, eventconceptname, eventCumulativenetworthEUR, eventtimetimestamp)

eventlog_cluster_wideafterbedragen <- eventlog_cluster_afterbedragen %>%
  group_by(caseconceptname) %>%
  summarise(PO_value = max(eventCumulativenetworthEUR[eventconceptname == "Create Purchase Order Item"], na.rm = TRUE),
            GR_value = max(eventCumulativenetworthEUR[eventconceptname == "Record Goods Receipt"], na.rm = TRUE),
            Invoice_value = max(eventCumulativenetworthEUR[eventconceptname %in% c("Vendor creates invoice", "Record Invoice Receipt")], na.rm = TRUE))

eventlog_cluster_wideafterbedragen <- eventlog_cluster_wideafterbedragen %>%
  mutate(three_way_match = PO_value == GR_value & GR_value == Invoice_value)

print(eventlog_cluster_wideafterbedragen)

false_count_after_threeway <- sum(eventlog_cluster_wideafterbedragen$three_way_match == FALSE, na.rm = TRUE)

```

```{r}
#kijken of de bedragen overeenkomen voor two way matching
eventlog_cluster_twowaybedragen <- eventlog_cluster_twoway %>%
  filter(eventconceptname %in% c("Vendor creates invoice", "Record Goods Receipt", "Record Invoice Receipt", "Create Purchase Order Item")) %>%
  select(caseconceptname, eventconceptname, eventCumulativenetworthEUR, eventtimetimestamp)

eventlog_cluster_widetwowaybedragen <- eventlog_cluster_twowaybedragen %>%
  group_by(caseconceptname) %>%
  summarise(PO_value = max(eventCumulativenetworthEUR[eventconceptname == "Create Purchase Order Item"], na.rm = TRUE),
            Invoice_value = max(eventCumulativenetworthEUR[eventconceptname %in% c("Vendor creates invoice", "Record Invoice Receipt")], na.rm = TRUE))

eventlog_cluster_widetwowaybedragen <- eventlog_cluster_widetwowaybedragen %>%
  mutate(three_way_match = PO_value == Invoice_value)

print(eventlog_cluster_widetwowaybedragen)

false_count_twoway <- sum(eventlog_cluster_widetwowaybedragen$three_way_match == FALSE, na.rm = TRUE)

```

```{r}
# precedence matrix geplot en niet geplot

processmapR::precedence_matrix(eventlog_exploratory)
processmapR::precedence_matrix(eventlog_exploratory) %>% plot
```

```{r}
# trace explorer for frequent traces

processmapR::trace_explorer(eventlog_cluster, n_traces = 5)
```

```{r}
# process map
processmapR::process_map(eventlog_cluster)
```

```{r}
# trace explorer for infrequent traces

processmapR::trace_explorer(eventlog_cluster, type = "infrequent", coverage = 0.1)
```


```{r}
# dotted chart

eventlog_cluster %>% dotted_chart(x = "relative")
```

```{r}

processmapR::precedence_matrix(eventlog_cluster) %>% plot

```